# 65 target cities — har ek ke liye 50 miles radius mein groups search hoga
# Naya city add karne ke baad `py build_area_cache.py` dobara chalao taake
# cache (areas_cache.json) update ho jaye.

AREAS = [
    "Waco Texas",
    "Midland Texas",
    "Lubbock Texas",
    "San Francisco California",
    "San Diego California",
    "Detroit Michigan",
    "Atlanta Georgia",
    "Knoxville Tennessee",
    "Nashville Tennessee",
    "Seattle Washington",
    "Sacramento California",
    "Richmond Virginia",
    "Valdosta Georgia",
    "Gainesville Florida",
    "Bakersfield California",
    "Boston Massachusetts",
    "Chicago Illinois",
    "Charlotte North Carolina",
    "Charleston South Carolina",
    "Columbia South Carolina",
    "Dallas Texas",
    "Fort Worth Texas",
    "Jacksonville Florida",
    "Oklahoma City Oklahoma",
    "San Antonio Texas",
    "Austin Texas",
    "Spokane Washington",
    "Tallahassee Florida",
    "Tucson Arizona",
    "Corpus Christi Texas",
    "New Haven Connecticut",
    "Hartford Connecticut",
    "Springfield Massachusetts",
    "Los Angeles California",
    "Phoenix Arizona",
    "Las Vegas Nevada",
    "Houston Texas",
    "College Station Texas",
    "Tampa Florida",
    "Orlando Florida",
    "Miami Florida",
    "Columbus Ohio",
    "Cincinnati Ohio",
    "Dayton Ohio",
    "Portland Oregon",
    "Washington DC",
    "New York",
    "New Jersey",
    "Indianapolis Indiana",
    "Minneapolis Minnesota",
    "Greenville South Carolina",
    "Philadelphia Pennsylvania",
    "Baltimore Maryland",
    "Rochester New York",
    "Rockford Illinois",
    "Allentown Pennsylvania",
    "Milwaukee Wisconsin",
    "Kansas City Missouri",
    "Raleigh North Carolina",
    "Omaha Nebraska",
    "Louisville Kentucky",
    "Savannah Georgia",
    "Salt Lake City Utah",
    "Pensacola Florida",
    "Fayetteville North Carolina",
]

# Har city ke liye yeh search terms use hote hain
SEARCH_TEMPLATES = [
    "{area} community",
    "{area} neighborhood",
    "{area} local residents",
    "{area} buy sell trade",
    "{area} community group",
]
